# Generated by Django 2.0 on 2018-08-13 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_cut',
            name='created_Date',
        ),
        migrations.RemoveField(
            model_name='short_cut',
            name='id',
        ),
        migrations.AddField(
            model_name='short_cut',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 23, 23, 2, 64173)),
        ),
        migrations.AlterField(
            model_name='short_cut',
            name='shortcut',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
