# Generated by Django 2.0 on 2018-08-13 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL_shortener_app', '0002_auto_20180813_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_cut',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 23, 23, 13, 442893)),
        ),
    ]
